server:
  port: 8080

spring:
  application:
    name: bets-dashboard

  datasource:
    url: jdbc:mysql://localhost:3306/bets_dashboard?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Lucker09@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect